fix the issue with pull from dockerhub before push

diff --git a/.github/workflows/use-custom-action.yml b/.github/workflows/use-custom-action.yml
--- a/.github/workflows/use-custom-action.yml
+++ b/.github/workflows/use-custom-action.yml
@@ -19,17 +19,19 @@ jobs:
               with:
                 username: ${{ secrets.docker_username }}
                 password: ${{ secrets.docker_hub_token }}
-#add a step that can only start after workflow A is completed
+#add a step that can only start after workflow A is completed the job
             - name: Wait for Workflow A completion
               run: echo "Waiting for Workflow A to complete..."
 
-                
-            - name: Check Workflow A status
+            - name: check workflow
               run: |
-                while [ "${{ steps.workflow_status.outputs.status }}" == "success" ]; then
-                done
+                echo "Workflow A status: ${{ github.event.workflow_run.conclusion }}"
+                if [ "${{ github.event.workflow_run.conclusion }}" != "success" ]; then
+                echo "Workflow A failed"
+                exit 1
+                fi
 
-                
+
 # pull the custom action from docker hub
             - name: pull and run
               run: |
